### ISSUE TITLE
Source Webcam 

### ISSUE THREAD

**Issue by belal-ibrahim** [jczarnowski/DeepFactors#15]
I am running some tests as ground truth for evaluations and i want to use my laptop webcam, Any idea how to source it?
Regards

**Comment by jczarnowski** [comment]
Hi belal-ibrahim,

To use your camera as input, you have to write a class that implements this interface:
https://github.com/jczarnowski/DeepFactors/blob/master/sources/drivers/camera/live_interface.h

You can use this class as an example:
https://github.com/jczarnowski/DeepFactors/blob/master/sources/drivers/camera/openni_interface.h
