### ISSUE TITLE
monocular camera

### ISSUE THREAD

**Issue by ghost** [jczarnowski/DeepFactors#16]
I want to experiment with image(video) data taken with a monocular camera.
Is it possible to do that?
If you can, please tell me what to do.
Regards

My camera is a RICOH THETA V and iphone.

**Comment by jczarnowski** [comment]
This system works only on monocular cameras, so yes, it will work with that data.

You could use the file interface to run the system on captured images:
```
build/bin/df_demo --flagfile=data/flags/dataset_odom.flags --source_url=filesrc://<glob path to your images>
```
You need to have the cameras calibrated and supply that to the system via parameters.
