### ISSUE TITLE
About pthread

### ISSUE THREAD

**Issue by PuYuuu** [jczarnowski/DeepFactors#17]
Hello, thank you for your work. And when i run the 'makedeps.sh' in thirdparty folder, i encountered the question, 'usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_getspecific@@GLIBC_2.2.5'', what should i do to solve it?

**Comment by empty2do** [comment]
I had the same problem. After adding SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread")
 after line 45 of thirdparty/camera_drivers/CMakeLists.txt , it solved the problem for me.
