### ISSUE TITLE
OptimizeRep may never get removed

### ISSUE THREAD

**Issue by rajy4683** [jczarnowski/DeepFactors#18]
Hello,
        First off thanks for the awesome code! Had thorough fun going through the code and using it. Found this one use case which, although unlikely, may happen:
In `OptimizeWork` the condition for `SignalRemove` is as below:

```
template <typename Scalar>
void OptimizeWork<Scalar>::Update()
{
  if (active_level_ >= 0 && --iters_[active_level_] < 0)
    active_level_ -= 1;

  if (remove_after_ && active_level_ < 0)
    SignalRemove();
}
```

However, OptimizeRep, never sets `remove_after` flag to true. So `SignalRemove` would never be invoked.
Another possible code path which works well for OptimizePhoto is through `SignalNoRelinearize` in `Mapper::MappingStep()`, when `isam_res_.variablesRelinearized == 0` is met. But that also wouldn't work here.
I am trying to reproduce this issue but am stuck because ReprojectionFactors don't get added for me at all in tum-d dataset (will probably raise a query if I am still not able to fix it). But I suppose the correct way to handle this code would be to implement Update() in the each of the child classes as opposed to OptimizeWork?

**Comment by jczarnowski** [comment]
Hi rajy4683,

Thanks for your kind words!

It's true that the mechanism for auto-removing the reprojection factor will not work, but this is intended for our current method. Auto-removing is meant to be requested in the constructors of the concrete implementation classes (OptimizePhoto) and it is simply not available for the other factors, for which we did not ever need using it.

As for the ReprojectionFactors not being added to the graph on TUM, you could try making sure that:
1) reprojection error is enabled in the config files
2) the features are being detected and matched -- thresholds need to be set correctly in the configs

**Comment by rajy4683** [comment]
Thanks Jan for the inputs. Will try accordingly. I will be closing this issue.
