### ISSUE TITLE
Do you  plan to release the train code?

### ISSUE THREAD

**Issue by pangfumin** [jczarnowski/DeepFactors#19]
@jczarnowski  Thanks for releasing this great work!
Do you plan to release the train code?

**Comment by jczarnowski** [comment]
Hi @pangfumin, thanks for the kind words!
I regret to say it will not be possible due to legal reasons relating to the sponsor of my PhD scholarship and my current employer..

**Comment by hjxwhy** [comment]
@pangfumin 你好，你有复现出来吗这个网络？
