### ISSUE TITLE
Running session failed: Conv2DCustomBackpropInputOp only supports NHWC.

### ISSUE THREAD

**Issue by zhlx007** [jczarnowski/DeepFactors#26]
dear jczarnowski:
       When I run the test data with "bash scripts / run_scan. Bash", the system outputs the following error:

  terminate called after throwing an instance of 'std::runtime_error'
  what():  Running session failed: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[{{node CNN/dpt_decode/dpt_std_pyr/pyr_0/conv2d_transpose}}]]
scripts/run_scannet.bash: line 102:  5729 Aborted                 (core dumped) ${df_bin} --flagfile=data/flags/dataset_odom.flags --source_url=scannet://${seq_dir}
~/Desktop/DeepFactors

Please help me！

**Comment by prasadvagdargi** [comment]
Same as #10

**Comment by zhlx007** [comment]
> Same as #10

CUDA is not running. Check the NVIDIA graphics driver

**Comment by jczarnowski** [comment]
Hi @zhlx007 

As @prasadvagdargi correctly observed, this issue is similar to #10. It occurs when your TensorFlow version was not compiled with GPU/CUDA support and tries to run the code with CPU only.
