### ISSUE TITLE
May I ask what is the principle of frame generation keyframe for marginalization?

### ISSUE THREAD

**Issue by hunkyu** [jczarnowski/DeepFactors#3]
May I ask what is the principle of frame generation keyframe for marginalization?

**Comment by jczarnowski** [comment]
Hi hunkyu,
Could you specify your question a bit? I'm not quite sure what you're asking about. 

The keyframes and frames are automatically spawned based on few different criteria such as image overlap or 3D distance. You can take a look at the functions `DeepFactors::NewKeyframeRequired()` and `DeepFactors::NewFrameRequired()` which determine exactly this -- when a new frame or keyframe should be crated.

**Comment by jczarnowski** [comment]
Closing this for now, please reopen with your reply.
