### ISSUE TITLE
Can not finish building properly, help please

### ISSUE THREAD

**Issue by Tetsujinfr** [jczarnowski/DeepFactors#6]
I have the below error at bulding. There are some CMake warnings but I cannot figure out if the build error is due to those warnings and what they mean neiher.
Can you help me?
(I am building everything under colab, CUDA version is 10.1 and CuDNN 7)

`
%cd /content/DeepFactors/
! mkdir build
% cd build
! cmake ..
! make

/content/DeepFactors
/content/DeepFactors/build
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
Project: deepfactors
Version: 0.1
Build type: Release
Compiled on: Linux-4.19.104+
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.2") 
-- Found GLEW: /usr/include  
-- GTSAM include directory:  /content/DeepFactors/thirdparty/install/lib/cmake/GTSAM/../../../include
-- Found Threads: TRUE  
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GTSAM include directory:  /content/DeepFactors/thirdparty/install/lib/cmake/GTSAM/../../../include
-- Found TensorFlow (include: /usr/local/include, library: /usr/local/lib/libtensorflow.so)
-- Autodetected CUDA architecture(s):  7.5
Compiling for CUDA architectures: -gencode;arch=compute_75,code=sm_75
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.17") 
-- Configuring done
CMake Warning at sources/core/CMakeLists.txt:81 (add_library):
  Cannot generate a safe runtime search path for target df_core because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libtbbmalloc.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib
    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /content/DeepFactors/build
Scanning dependencies of target df_common
[  1%] Building CXX object sources/common/CMakeFiles/df_common.dir/image_sequences.cpp.o
[  3%] Building CXX object sources/common/CMakeFiles/df_common.dir/timing.cpp.o
...
[ 66%] Built target df_drivers
Scanning dependencies of target df_demo
[ 67%] Building CXX object sources/demo/CMakeFiles/df_demo.dir/main.cpp.o
[ 69%] Building CXX object sources/demo/CMakeFiles/df_demo.dir/live_demo.cpp.o
[ 70%] Linking CXX executable ../../bin/df_demo
/usr/lib/x86_64-linux-gnu/libGL.so: undefined reference to `_glapi_tls_Current'
collect2: error: ld returned 1 exit status
sources/demo/CMakeFiles/df_demo.dir/build.make:185: recipe for target 'bin/df_demo' failed
make[2]: *** [bin/df_demo] Error 1
CMakeFiles/Makefile2:352: recipe for target 'sources/demo/CMakeFiles/df_demo.dir/all' failed
make[1]: *** [sources/demo/CMakeFiles/df_demo.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by jczarnowski** [comment]
This looks like an issue specific to trying to build it in colab. It's hard for me to comment on what is going on here as I do not know the configuration of the OS there. 

It might be that they do not have the right GL installed.
